// Generated by Wrangler on Sun Jul 07 2024 15:50:07 GMT-0500 (Central Daylight Time)
// by running `wrangler types`

export interface Env {
  TF_STATE_LOCK: DurableObjectNamespace;
  TF_STATE_BUCKET: R2Bucket;
}
